-- CreateEnum
CREATE TYPE "ZapStatus" AS ENUM ('ACTIVE', 'PAUSED', 'DRAFT');

-- AlterTable
ALTER TABLE "Zap" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "name" TEXT NOT NULL DEFAULT 'unnamed-workflow',
ADD COLUMN     "status" "ZapStatus" NOT NULL DEFAULT 'DRAFT',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
